//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatelliteTest.Satellite {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Satellite.ISatellite")]
    public interface ISatellite {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISatellite/Process", ReplyAction="http://tempuri.org/ISatellite/ProcessResponse")]
        void Process(string template, System.Collections.Generic.Dictionary<string, string> parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISatellite/Process", ReplyAction="http://tempuri.org/ISatellite/ProcessResponse")]
        System.Threading.Tasks.Task ProcessAsync(string template, System.Collections.Generic.Dictionary<string, string> parameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISatelliteChannel : SatelliteTest.Satellite.ISatellite, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SatelliteClient : System.ServiceModel.ClientBase<SatelliteTest.Satellite.ISatellite>, SatelliteTest.Satellite.ISatellite {
        
        public SatelliteClient() {
        }
        
        public SatelliteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SatelliteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SatelliteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SatelliteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Process(string template, System.Collections.Generic.Dictionary<string, string> parameters) {
            base.Channel.Process(template, parameters);
        }
        
        public System.Threading.Tasks.Task ProcessAsync(string template, System.Collections.Generic.Dictionary<string, string> parameters) {
            return base.Channel.ProcessAsync(template, parameters);
        }
    }
}
